### ISSUE TITLE
Improve existing documentation 

### ISSUE THREAD

**Issue by inirah02** [Mikhaela-Paige/Getting-Started-with-Python#11]
I think the current documentation can be elaborated and thus make it more useful for all the contributors. I'd love to incorporate useful resources and edit the pre-existing content as my proposal.

**Comment by Mikhaela-Paige** [comment]
Great idea! That would be much appreciated, thank you

**Comment by inirah02** [comment]
Thank you for your response! I'll get to it by the end of the day :)

**Comment by inirah02** [comment]
ReadME.md has been successfully updated.
